### PR TITLE
make sure that python2.7 is used

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**

### CODE REVIEW

**Comment by benmwebb** [comment]
I'm curious to know why this is necessary - IMP itself should work fine with both Python 2 and Python 3, and (unless @Pellarin broke something recently) our tutorials work with either Python too.

**Comment by Pellarin** [comment]
I haven’t broke anything :-) it is just for the Binder thing. But probably you’re right, we don’t need it.

**Comment by benmwebb** [comment]
> I haven’t broke anything :-)

I see a lot of `print "foo"` type statements in your new plotting/analysis scripts, which won't work in Python 3.

If you have to pick a specific Python version, I would go for Python 3.6, since 2.7 will be going out of support in the not too distant future. And anybody running the tutorial on Windows is probably going to pick Python 3 anyway, since there's no system Python to conflict with and users tend to just pick the "latest and greatest" by default.

**Comment by Pellarin** [comment]
Yes, just in the tutorial though.

**Comment by truatpasteurdotfr** [comment]
closing PR as not needed

**Pull request closed without merging**
